apiVersion: v1
data:
  proxy-set-headers: "ingress/custom-headers"
kind: ConfigMap
metadata:
  name: nginx-ingress-microk8s-controller
  namespace: ingress
  labels:
    app.kubernetes.io/name: ingress
    app.kubernetes.io/part-of: ingress

