apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    app: qbittorrent
  name: qbittorrent
  selfLink: /apis/apps/v1/namespaces/default/deployments/qbittorrent
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: qbittorrent
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: qbittorrent
    spec:
      containers:
      - image: linuxserver/qbittorrent
        imagePullPolicy: Always
        name: qbittorrent
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
        - containerPort: 8080
        env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        volumeMounts:
        - name: qbittorrent
          mountPath: /config
        - name: qbittorrent-download
          mountPath: /download
      volumes:
      - name: qbittorrent
        hostPath:
          path: /media/Config/qbittorrent
      - name: qbittorrent-download
        hostPath:
          path: /media/Downloads
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
